<?php
    include("includes/db_con.php");
    include("includes/sql.php");
    include("includes/menu.php");
    //html
    include("includes/header.php");
    include($content);
    include("includes/footer.php");
?>